#cloud-config
write_files:
- path: /etc/sysctl.d/98-ip-forward.conf
  content: |
    net.ipv4.ip_forward = 1
runcmd:
  - apt-get update
  - apt install -y firewalld
  - firewall-offline-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -o enp0s3 -j MASQUERADE
  - firewall-offline-cmd --direct --add-rule ipv4 filter FORWARD 0 -i enp0s3 -j ACCEPT
  - /bin/systemctl restart firewalld
  - sysctl -p /etc/sysctl.d/98-ip-forward.conf